### ISSUE TITLE
多级服务调用的路由执行灰度路由执行报错

### ISSUE THREAD

**Issue by syq17** [Nepxion/Discovery#12]
测试系统调用如下：zuul -> channel-server -> order-server
在zuul上执行灰度路由，将channel-server和order-server一同选中，执行则会报错。
zuul服务报如下错误：
`Caused by: com.fasterxml.jackson.databind.JsonMappingException: Can not construct instance of java.util.LinkedHashMap: no String-argument constructor/factory method to deserialize from String value ('')
 at [Source: [{"serviceId":"order-server","version":"1.0","region":"","host":"10.10.2.19","port":8603,"weight":-1,"customMap":"","contextPath":"/","nexts":[]}]; line: 1, column: 114] (through reference chain: java.util.ArrayList[0]->com.nepxion.discovery.common.entity.RouterEntity["customMap"])
	at com.fasterxml.jackson.databind.JsonMappingException.from(JsonMappingException.java:270) ~[jackson-databind-2.8.11.2.jar:2.8.11.2]
	at com.fasterxml.jackson.databind.DeserializationContext.instantiationException(DeserializationContext.java:1469) ~[jackson-databind-2.8.11.2.jar:2.8.11.2]
	at com.fasterxml.jackson.databind.DeserializationContext.handleMissingInstantiator(DeserializationContext.java:1012) ~[jackson-databind-2.8.11.2.jar:2.8.11.2]
	at com.fasterxml.jackson.databind.deser.ValueInstantiator._createFromStringFallbacks(ValueInstantiator.java:371) ~[jackson-databind-2.8.11.2.jar:2.8.11.2]
	at com.fasterxml.jackson.databind.deser.std.StdValueInstantiator.createFromString(StdValueInstantiator.java:324) ~[jackson-databind-2.8.11.2.jar:2.8.11.2]
	at com.fasterxml.jackson.databind.deser.std.MapDeserializer.deserialize(MapDeserializer.java:355) ~[jackson-databind-2.8.11.2.jar:2.8.11.2]
	at com.fasterxml.jackson.databind.deser.std.MapDeserializer.deserialize(MapDeserializer.java:27) ~[jackson-databind-2.8.11.2.jar:2.8.11.2]
	at com.fasterxml.jackson.databind.deser.SettableBeanProperty.deserialize(SettableBeanProperty.java:504) ~[jackson-databind-2.8.11.2.jar:2.8.11.2]
	at com.fasterxml.jackson.databind.deser.impl.MethodProperty.deserializeAndSet(MethodProperty.java:104) ~[jackson-databind-2.8.11.2.jar:2.8.11.2]
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.vanillaDeserialize(BeanDeserializer.java:276) ~[jackson-databind-2.8.11.2.jar:2.8.11.2]
	at com.fasterxml.jackson.databind.deser.BeanDeserializer.deserialize(BeanDeserializer.java:140) ~[jackson-databind-2.8.11.2.jar:2.8.11.2]
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:287) ~[jackson-databind-2.8.11.2.jar:2.8.11.2]
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:259) ~[jackson-databind-2.8.11.2.jar:2.8.11.2]
	at com.fasterxml.jackson.databind.deser.std.CollectionDeserializer.deserialize(CollectionDeserializer.java:26) ~[jackson-databind-2.8.11.2.jar:2.8.11.2]
	at com.fasterxml.jackson.databind.ObjectMapper._readMapAndClose(ObjectMapper.java:3814) ~[jackson-databind-2.8.11.2.jar:2.8.11.2]
	at com.fasterxml.jackson.databind.ObjectMapper.readValue(ObjectMapper.java:2877) ~[jackson-databind-2.8.11.2.jar:2.8.11.2]
	at com.nepxion.discovery.common.util.JsonUtil.fromJson(JsonUtil.java:58) ~[discovery-common-3.7.6.jar:?]`
报错原因为/router/route/order-server/接口返回json中customMap字段为"",而对应的解析类RouterEntity为Map类型，无法反序列化。
全链路规则为：
`<?xml version="1.0" encoding="UTF-8"?>
<rule>
    <discovery>
        <version>
            <service consumer-service-name="channel-server" provider-service-name="account-server" consumer-version-value="1.0" provider-version-value="1.0"/>
            <service consumer-service-name="channel-server" provider-service-name="order-server" consumer-version-value="1.0" provider-version-value="1.0"/>
            <service consumer-service-name="api-gateway" provider-service-name="channel-server" consumer-version-value="1.0" provider-version-value="1.0"/>
        </version>
    </discovery>
</rule>`
希望作者大大帮忙看下，谢谢

**Comment by HaojunRen** [comment]
刚看到这个问题就关闭了，请问解决了么？
