### ISSUE TITLE
FeignStrategyInterceptor IllegalArgumentException

### ISSUE THREAD

**Issue by generalrbb** [Nepxion/Discovery#207]
java.lang.IllegalArgumentException
message:
an expression is required.
stack:
java.lang.IllegalArgumentException: an expression is required.
at feign.template.Expressions.create(Expressions.java:50)
at feign.template.Template.parseFragment(Template.java:224)
at feign.template.Template.parseTemplate(Template.java:203)
at feign.template.Template.<init>(Template.java:70)
at feign.template.HeaderTemplate.<init>(HeaderTemplate.java:81)
at feign.template.HeaderTemplate.create(HeaderTemplate.java:57)
at feign.RequestTemplate.lambda$appendHeader$2(RequestTemplate.java:693)
at java.util.Map.compute(Map.java:1093)
at feign.RequestTemplate.appendHeader(RequestTemplate.java:691)
at feign.RequestTemplate.header(RequestTemplate.java:675)
at feign.RequestTemplate.header(RequestTemplate.java:657)
at com.nepxion.discovery.plugin.strategy.service.aop.FeignStrategyInterceptor.applyInnerHeader(FeignStrategyInterceptor.java:64)
at com.nepxion.discovery.plugin.strategy.service.aop.FeignStrategyInterceptor.apply(FeignStrategyInterceptor.java:49)
at feign.SynchronousMethodHandler.targetRequest(SynchronousMethodHandler.java:171)
at feign.SynchronousMethodHandler.executeAndDecode(SynchronousMethodHandler.java:101)
at feign.SynchronousMethodHandler.invoke(SynchronousMethodHandler.java:80)
at feign.ReflectiveFeign$FeignInvocationHandler.invoke(ReflectiveFeign.java:103)

**Comment by HaojunRen** [comment]
What's the version of Nepxion Discovery? Maybe your heads have special character?

**Comment by HaojunRen** [comment]
Refer to `feign.template.Expressions`
```java
  public static Expression create(final String value) {

    /* remove the start and end braces */
    final String expression = stripBraces(value);
    if (expression == null || expression.isEmpty()) {
      throw new IllegalArgumentException("an expression is required.");
    }

    ...
```

```java
  private static String stripBraces(String expression) {
    if (expression == null) {
      return null;
    }
    if (expression.startsWith("{") && expression.endsWith("}")) {
      return expression.substring(1, expression.length() - 1);
    }
    return expression;
  }
```

I guess your value is '{}'?
